module.exports = {
    version: "0.2",
    language: "en,pt,pt_BR",
    import: ["@cspell/dict-pt-br/cspell-ext.json"],
    dictionaryDefinitions: [
        {
            name: "project-words",
            path: "./project-words.txt",
            addWords: true,
        },
    ],
    dictionaries: [
        "typescript",
        "node",
        "npm",
        "html",
        "css",
        "fonts",
        "filetypes",
        "companies",
        "softwareTerms",
        "pt-br",
        "en-us",
        "project-words",
    ],
    words: [
        // Personal/Project
        "gabrieltoth",
        "framesync",
        "ViraTrend",
        "SpeedPC",
        "waveigl",

        // Tech Stack
        "vercel",
        "nextjs",
        "tailwindcss",
        "shadcn",
        "eslint",
        "prettier",
        "cspell",
        "husky",
        "commitlint",
        "typescript",
        "javascript",
        "reactjs",
        "nodejs",

        // Databases
        "mongodb",
        "postgresql",
        "redis",
        "planetscale",
        "prisma",
        "supabase",

        // Infrastructure
        "docker",
        "kubernetes",
        "aws",
        "azure",
        "gcp",
        "netlify",
        "herokuapp",
        "firebase",

        // Development
        "fullstack",
        "frontend",
        "backend",
        "devops",
        "cicd",
        "trpc",
        "nextauth",
        "clerk",
        "headless",
        "jamstack",
        "serverless",
        "microservices",
        "monorepo",
        "turborepo",

        // Build Tools
        "vite",
        "webpack",
        "rollup",
        "esbuild",
        "swc",
        "babel",
        "postcss",
        "autoprefixer",
        "pnpm",
        "yarn",
        "npm",
        "node",
        "deno",
        "bun",

        // Services
        "stripe",
        "paypal",
        "emailjs",
        "resend",
        "sanity",
        "contentful",
        "storyblok",
        "strapi",

        // Social/Platforms
        "linkedin",
        "github",
        "gmail",
        "youtube",
        "instagram",
        "whatsapp",
        "twitch",
        "discord",
        "figma",
        "bhsl",
    ],
    ignorePaths: [
        "node_modules/**",
        ".next/**",
        "dist/**",
        "build/**",
        "*.min.js",
        "*.min.css",
        "package-lock.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        ".git/**",
        "*.svg",
        "*.png",
        "*.jpg",
        "*.jpeg",
        "*.webp",
        "*.ico",
        "*.woff",
        "*.woff2",
        "*.ttf",
        "*.otf",
        "cspell.config.js",
    ],
    enableFiletypes: [
        "typescript",
        "typescriptreact",
        "javascript",
        "javascriptreact",
        "json",
        "markdown",
        "text",
        "html",
        "css",
        "scss",
        "sass",
        "less",
    ],
    allowCompoundWords: true,
    caseSensitive: false,
    ignoreRegExpList: [
        "/\\b[A-Z]{2,}\\b/g",
        "/\\b\\d+\\b/g",
        "/\\b[a-f0-9]{8,}\\b/gi",
        "/\\bhex[a-f0-9]+\\b/gi",
        "/\\b#[a-f0-9]{3,8}\\b/gi",
        "/\\bhsl\\([^)]+\\)/gi",
        "/\\brgb\\([^)]+\\)/gi",
        "/\\burl\\([^)]+\\)/gi",
        "/\\bvar\\([^)]+\\)/gi",
        "/\\bcalc\\([^)]+\\)/gi",
        "/\\b[a-z]+-[a-z0-9-]+\\b/gi",
        "/\\btw-[a-z0-9-]+\\b/gi",
        "/\\bcn\\([^)]*\\)/gi",
        "/\\bclsx\\([^)]*\\)/gi",
        "/\\btwMerge\\([^)]*\\)/gi",
    ],
}
