module.exports = {
    version: "0.2",
    language: "en,pt,pt_BR",
    import: ["@cspell/dict-pt-br/cspell-ext.json"],
    dictionaryDefinitions: [
        {
            name: "project-words",
            path: "./project-words.txt",
            addWords: true,
        },
    ],
    dictionaries: [
        "typescript",
        "node",
        "npm",
        "html",
        "css",
        "fonts",
        "filetypes",
        "companies",
        "softwareTerms",
        "pt-br",
        "en-us",
        "project-words",
    ],
    words: [
        "oprimeirogabrieltoth",
        "portifolio",
        "lgpd",
        "sitemapindex",
        "subcomponents",
        "tecnico",
        "Googlebot",
        "Bingbot",
        "facebookexternalhit",
        "Twitterbot",
    ],
    ignorePaths: [
        "node_modules/**",
        ".next/**",
        "dist/**",
        "build/**",
        "*.min.js",
        "*.min.css",
        "package-lock.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        ".git/**",
        "*.svg",
        "*.png",
        "*.jpg",
        "*.jpeg",
        "*.webp",
        "*.ico",
        "*.woff",
        "*.woff2",
        "*.ttf",
        "*.otf",
        "cspell.config.js",
    ],
    enableFiletypes: [
        "typescript",
        "typescriptreact",
        "javascript",
        "javascriptreact",
        "json",
        "markdown",
        "text",
        "html",
        "css",
        "scss",
        "sass",
        "less",
    ],
    allowCompoundWords: true,
    caseSensitive: false,
    ignoreRegExpList: [
        "/\\b[A-Z]{2,}\\b/g",
        "/\\b\\d+\\b/g",
        "/\\b[a-f0-9]{8,}\\b/gi",
        "/\\bhex[a-f0-9]+\\b/gi",
        "/\\b#[a-f0-9]{3,8}\\b/gi",
        "/\\bhsl\\([^)]+\\)/gi",
        "/\\brgb\\([^)]+\\)/gi",
        "/\\burl\\([^)]+\\)/gi",
        "/\\bvar\\([^)]+\\)/gi",
        "/\\bcalc\\([^)]+\\)/gi",
        "/\\b[a-z]+-[a-z0-9-]+\\b/gi",
        "/\\btw-[a-z0-9-]+\\b/gi",
        "/\\bcn\\([^)]*\\)/gi",
        "/\\bclsx\\([^)]*\\)/gi",
        "/\\btwMerge\\([^)]*\\)/gi",
    ],
}
