import { type Locale } from "@/lib/i18n"
import { generateSeoConfig } from "@/lib/seo"
import { type Metadata } from "next"

interface PageProps {
    params: Promise<{ locale: Locale }>
}

export async function generateMetadata({
    params,
}: PageProps): Promise<Metadata> {
    const { locale } = await params
    const isPortuguese = locale === "pt-BR"

    const seoConfig = generateSeoConfig({
        locale,
        path: "/editors",
        title: isPortuguese
            ? "Trabalhe Como Editor de Vídeo - 90% do AdSense - Gabriel Toth"
            : "Work as Video Editor - 90% AdSense Revenue - Gabriel Toth",
        description: isPortuguese
            ? "Junte-se à nossa equipe de editores e ganhe 90% do AdSense gerado pelos vídeos que você editar. Trabalho flexível, pagamento por performance e projetos interessantes."
            : "Join our video editing team and earn 90% of AdSense generated by videos you edit. Flexible work, performance-based payment and interesting projects.",
        keywords: isPortuguese
            ? [
                  "editor de vídeo",
                  "trabalho remoto",
                  "adsense",
                  "pagamento por performance",
                  "edição youtube",
                  "freelancer",
                  "gabriel toth",
                  "trabalho flexível",
              ]
            : [
                  "video editor",
                  "remote work",
                  "adsense",
                  "performance payment",
                  "youtube editing",
                  "freelancer",
                  "gabriel toth",
                  "flexible work",
              ],
        ogType: "article",
        ogImage: "https://gabrieltoth.com/og-image-editors.jpg",
    })

    return {
        title: seoConfig.title,
        description: seoConfig.description,
        keywords: seoConfig.additionalMetaTags?.find(
            tag => tag.name === "keywords"
        )?.content,
        robots: seoConfig.additionalMetaTags?.find(tag => tag.name === "robots")
            ?.content,
        openGraph: {
            title: seoConfig.openGraph?.title,
            description: seoConfig.openGraph?.description,
            url: seoConfig.canonical,
            type: seoConfig.openGraph?.type as "website",
            locale: seoConfig.openGraph?.locale,
            images: seoConfig.openGraph?.images?.map(img => ({
                url: img.url!,
                width: img.width,
                height: img.height,
                alt: img.alt!,
                type: img.type,
            })),
            siteName: "Gabriel Toth Portfolio",
        },
        twitter: {
            card: seoConfig.twitter?.card as "summary_large_image",
            title: seoConfig.twitter?.title,
            description: seoConfig.twitter?.description,
            images: seoConfig.twitter?.images,
            creator: seoConfig.twitter?.creator,
            site: seoConfig.twitter?.site,
        },
        alternates: {
            canonical: seoConfig.canonical,
            languages: {
                en: "https://gabrieltoth.com/editors",
                "pt-BR": "https://gabrieltoth.com/pt-BR/editors",
                "x-default": "https://gabrieltoth.com/editors",
            },
        },
    }
}
