import { PageProps } from "@/app/[locale]/editors/editors-types"
import Footer from "@/components/layout/footer"
import StructuredData from "@/components/seo/structured-data"
import Breadcrumbs from "@/components/ui/breadcrumbs"
import LanguageSelector from "@/components/ui/language-selector"
import { generateMetadata } from "./editors-metadata"
import { getEditorsTranslations } from "./editors-translations"
import {
    AboutSection,
    BenefitsSection,
    CTASection,
    HeroSection,
    RequirementsSection,
    ToolsSection,
} from "./editors-view"

export { generateMetadata }

export default async function EditorsPage({ params }: PageProps) {
    const { locale } = await params
    const isPortuguese = locale === "pt-BR"
    const t = await getEditorsTranslations(locale)

    // Job posting structured data
    const jobStructuredData = {
        "@context": "https://schema.org",
        "@type": "JobPosting",
        title: isPortuguese
            ? "Editor de Vídeo Freelancer"
            : "Freelance Video Editor",
        description: isPortuguese
            ? "Oportunidade única de trabalhar como editor de vídeo e ganhar 90% do AdSense dos vídeos editados"
            : "Unique opportunity to work as a video editor and earn 90% of AdSense from edited videos",
        hiringOrganization: {
            "@type": "Organization",
            name: "Gabriel Toth Gonçalves",
            sameAs: "https://gabrieltoth.com",
        },
        datePosted: "2024-12-15",
        employmentType: "CONTRACTOR",
        workHours: isPortuguese ? "Horário flexível" : "Flexible hours",
        jobLocation: {
            "@type": "Place",
            address: {
                "@type": "PostalAddress",
                addressCountry: "BR",
                addressRegion: "São Paulo",
            },
        },
        baseSalary: {
            "@type": "MonetaryAmount",
            currency: "BRL",
            value: {
                "@type": "QuantitativeValue",
                unitText: isPortuguese
                    ? "90% do AdSense por vídeo"
                    : "90% of AdSense per video",
            },
        },
        qualifications: isPortuguese
            ? "Experiência em edição de vídeo, conhecimento em softwares de edição"
            : "Video editing experience, knowledge of editing software",
        responsibilities: isPortuguese
            ? "Editar vídeos para YouTube, aplicar thumbnails, otimizar para SEO"
            : "Edit videos for YouTube, apply thumbnails, optimize for SEO",
    }

    // FAQs
    const faqs = isPortuguese
        ? [
              {
                  question: "Como funciona o pagamento de 90% do AdSense?",
                  answer: "Você recebe 90% de toda a receita do AdSense gerada pelos vídeos que editar. O pagamento é feito mensalmente via PIX.",
              },
              {
                  question: "Preciso ter equipamentos específicos?",
                  answer: "Você precisa de um computador capaz de rodar softwares de edição e conexão estável com internet para upload dos vídeos.",
              },
              {
                  question: "Quanto posso ganhar por mês?",
                  answer: "Os ganhos variam conforme a performance dos vídeos. Editores experientes podem ganhar entre R$ 2.000 a R$ 8.000+ por mês.",
              },
              {
                  question: "Como é o processo seletivo?",
                  answer: "Analisamos seu portfólio, fazemos um teste prático de edição e uma entrevista para avaliar compatibilidade.",
              },
          ]
        : [
              {
                  question: "How does the 90% AdSense payment work?",
                  answer: "You receive 90% of all AdSense revenue generated by the videos you edit. Payment is made monthly via PIX.",
              },
              {
                  question: "Do I need specific equipment?",
                  answer: "You need a computer capable of running editing software and stable internet connection for video uploads.",
              },
              {
                  question: "How much can I earn per month?",
                  answer: "Earnings vary according to video performance. Experienced editors can earn between R$ 2,000 to R$ 8,000+ per month.",
              },
              {
                  question: "What is the selection process like?",
                  answer: "We analyze your portfolio, conduct a practical editing test and an interview to assess compatibility.",
              },
          ]

    // Breadcrumbs
    const breadcrumbs = [
        {
            name: isPortuguese ? "Início" : "Home",
            url: `https://gabrieltoth.com/${locale}`,
        },
        {
            name: isPortuguese ? "Oportunidades" : "Opportunities",
            url: `https://gabrieltoth.com/${locale}/#opportunities`,
        },
        {
            name: isPortuguese ? "Trabalhe Como Editor" : "Work as Editor",
            url: `https://gabrieltoth.com/${locale}/editors`,
        },
    ]

    return (
        <>
            <StructuredData
                locale={locale}
                type="all"
                customData={jobStructuredData}
                breadcrumbs={breadcrumbs}
                faqs={faqs}
            />

            <div className="min-h-screen bg-white dark:bg-gray-900">
                {/* Language Selector for Landing Page */}
                <div className="container mx-auto px-4 py-4 flex justify-end">
                    <LanguageSelector />
                </div>

                <div className="container mx-auto px-4 pb-8">
                    <Breadcrumbs className="mb-6" />
                    <main className="flex min-h-screen flex-col items-center justify-between">
                        <HeroSection t={t} />
                        <AboutSection t={t} />
                        <ToolsSection t={t} />
                        <RequirementsSection t={t} />
                        <BenefitsSection t={t} />
                        <CTASection t={t} />
                    </main>
                </div>
                <Footer locale={locale} />
            </div>
        </>
    )
}
