import { PageProps } from "@/app/[locale]/editors/editors-types"
import StructuredData from "@/components/seo/structured-data"
import Breadcrumbs from "@/components/ui/breadcrumbs"
import { generateMetadata } from "./editors-metadata"
import { getEditorsTranslations } from "./editors-translations"
import {
    AboutSection,
    BenefitsSection,
    CTASection,
    HeroSection,
    RequirementsSection,
    ToolsSection,
} from "./editors-view"

export { generateMetadata }

export default async function EditorsPage({ params }: PageProps) {
    const { locale } = await params
    const isPortuguese = locale === "pt-BR"
    const t = await getEditorsTranslations(locale)

    // Job posting structured data
    const jobStructuredData = {
        "@context": "https://schema.org",
        "@type": "JobPosting",
        title: isPortuguese
            ? "Editor de Vídeo Freelancer"
            : "Freelance Video Editor",
        description: isPortuguese
            ? "Oportunidade única de trabalhar como editor de vídeo e ganhar 90% do AdSense dos vídeos editados"
            : "Unique opportunity to work as video editor and earn 90% of AdSense from edited videos",
        hiringOrganization: {
            "@type": "Person",
            name: "Gabriel Toth Gonçalves",
            url: "https://gabrieltoth.com",
        },
        jobLocation: {
            "@type": "Place",
            address: {
                "@type": "PostalAddress",
                addressCountry: "BR",
            },
        },
        employmentType: "CONTRACTOR",
        workHours: "Flexible",
        baseSalary: {
            "@type": "MonetaryAmount",
            currency: "BRL",
            value: {
                "@type": "QuantitativeValue",
                value: "Variable based on performance",
            },
        },
        responsibilities: isPortuguese
            ? "Editar vídeos com qualidade profissional, seguir briefings, entregar no prazo"
            : "Edit videos with professional quality, follow briefs, deliver on time",
        qualifications: isPortuguese
            ? "Experiência em edição de vídeo, conhecimento em software de edição, criatividade"
            : "Video editing experience, editing software knowledge, creativity",
    }

    // FAQ data
    const faqs = isPortuguese
        ? [
              {
                  question: "Como funciona o pagamento de 90% do AdSense?",
                  answer: "Você recebe 90% de toda a receita do AdSense gerada pelos vídeos que editar. O pagamento é feito mensalmente via PIX ou transferência bancária.",
              },
              {
                  question: "Preciso ter equipamentos específicos?",
                  answer: "Você precisa de um computador com capacidade para edição de vídeo e software de edição (Adobe Premiere, DaVinci Resolve, etc.).",
              },
              {
                  question: "Qual o volume de trabalho?",
                  answer: "O volume é flexível e baseado na sua disponibilidade. Pode variar de alguns vídeos por semana a projetos maiores.",
              },
          ]
        : [
              {
                  question: "How does the 90% AdSense payment work?",
                  answer: "You receive 90% of all AdSense revenue generated by videos you edit. Payment is made monthly via bank transfer or digital payment.",
              },
              {
                  question: "Do I need specific equipment?",
                  answer: "You need a computer capable of video editing and editing software (Adobe Premiere, DaVinci Resolve, etc.).",
              },
              {
                  question: "What's the work volume?",
                  answer: "Volume is flexible and based on your availability. Can range from a few videos per week to larger projects.",
              },
          ]

    // Breadcrumbs
    const breadcrumbs = [
        {
            name: isPortuguese ? "Início" : "Home",
            url: `https://gabrieltoth.com/${locale}`,
        },
        {
            name: isPortuguese ? "Oportunidades" : "Opportunities",
            url: `https://gabrieltoth.com/${locale}/#opportunities`,
        },
        {
            name: isPortuguese ? "Trabalhe Como Editor" : "Work as Editor",
            url: `https://gabrieltoth.com/${locale}/editors`,
        },
    ]

    return (
        <>
            <StructuredData
                locale={locale}
                type="all"
                customData={jobStructuredData}
                breadcrumbs={breadcrumbs}
                faqs={faqs}
            />

            <div className="min-h-screen bg-white dark:bg-gray-900">
                <div className="container mx-auto px-4 py-8">
                    <Breadcrumbs
                        items={breadcrumbs.map(item => ({
                            name: item.name,
                            href: item.url.replace(
                                "https://gabrieltoth.com",
                                ""
                            ),
                        }))}
                        className="mb-6"
                    />

                    <main className="flex min-h-screen flex-col items-center justify-between">
                        <HeroSection t={t} />
                        <AboutSection t={t} />
                        <ToolsSection t={t} />
                        <RequirementsSection t={t} />
                        <BenefitsSection t={t} />
                        <CTASection t={t} />
                    </main>
                </div>
            </div>
        </>
    )
}
