import { type Locale } from "@/lib/i18n"

interface TermsOfServicePageProps {
    params: Promise<{ locale: Locale }>
}

export default async function TermsOfServicePage({
    params,
}: TermsOfServicePageProps) {
    const { locale } = await params
    const isPortuguese = locale === "pt-BR"

    const content = {
        title: isPortuguese ? "Termos de Serviço" : "Terms of Service",
        lastUpdated: isPortuguese
            ? "Última atualização: Janeiro 2024"
            : "Last updated: January 2024",
        sections: {
            intro: {
                title: isPortuguese
                    ? "1. Aceitação dos Termos"
                    : "1. Acceptance of Terms",
                content: isPortuguese
                    ? "Ao contratar nossos serviços, você concorda em estar vinculado a estes Termos de Serviço. Se você não concorda com algum termo, não deve utilizar nossos serviços."
                    : "By hiring our services, you agree to be bound by these Terms of Service. If you do not agree with any term, you should not use our services.",
            },
            services: {
                title: isPortuguese
                    ? "2. Descrição dos Serviços"
                    : "2. Service Description",
                content: isPortuguese
                    ? [
                          "• Consultoria para crescimento de canais no YouTube e outras plataformas",
                          "• Otimização de performance de PCs para gaming e trabalho",
                          "• Serviços de edição de vídeos com remuneração baseada em AdSense",
                          "• Desenvolvimento de soluções tecnológicas personalizadas",
                          "• Suporte técnico e consultoria em projetos digitais",
                      ]
                    : [
                          "• Consulting for channel growth on YouTube and other platforms",
                          "• PC performance optimization for gaming and work",
                          "• Video editing services with AdSense-based compensation",
                          "• Custom technology solution development",
                          "• Technical support and digital project consulting",
                      ],
            },
            obligations: {
                title: isPortuguese
                    ? "3. Obrigações do Cliente"
                    : "3. Client Obligations",
                content: isPortuguese
                    ? [
                          "• Fornecer informações precisas e completas",
                          "• Cooperar durante o processo de consultoria",
                          "• Efetuar pagamentos conforme acordado",
                          "• Respeitar direitos autorais e propriedade intelectual",
                          "• Não usar serviços para atividades ilegais",
                      ]
                    : [
                          "• Provide accurate and complete information",
                          "• Cooperate during the consulting process",
                          "• Make payments as agreed",
                          "• Respect copyrights and intellectual property",
                          "• Not use services for illegal activities",
                      ],
            },
            payment: {
                title: isPortuguese
                    ? "4. Pagamentos e Reembolsos"
                    : "4. Payments and Refunds",
                content: isPortuguese
                    ? "Os pagamentos devem ser efetuados conforme acordado. Para editores, o pagamento é baseado em 90% do AdSense gerado pelos vídeos editados. Reembolsos são analisados caso a caso, considerando o trabalho já realizado."
                    : "Payments must be made as agreed. For editors, payment is based on 90% of AdSense generated by edited videos. Refunds are analyzed case by case, considering work already performed.",
            },
            liability: {
                title: isPortuguese
                    ? "5. Limitação de Responsabilidade"
                    : "5. Limitation of Liability",
                content: isPortuguese
                    ? "Nossos serviços são prestados com base no melhor esforço. Não garantimos resultados específicos de crescimento ou performance. Nossa responsabilidade é limitada ao valor dos serviços contratados."
                    : "Our services are provided on a best effort basis. We do not guarantee specific growth or performance results. Our liability is limited to the value of contracted services.",
            },
            intellectual: {
                title: isPortuguese
                    ? "6. Propriedade Intelectual"
                    : "6. Intellectual Property",
                content: isPortuguese
                    ? "Todo conteúdo criado durante nossos serviços pertence ao cliente, exceto metodologias e conhecimentos pré-existentes que permanecem de nossa propriedade."
                    : "All content created during our services belongs to the client, except for pre-existing methodologies and knowledge that remain our property.",
            },
            confidentiality: {
                title: isPortuguese
                    ? "7. Confidencialidade"
                    : "7. Confidentiality",
                content: isPortuguese
                    ? "Mantemos absoluta confidencialidade sobre informações do cliente, incluindo estratégias, dados de canal e informações comerciais sensíveis."
                    : "We maintain absolute confidentiality about client information, including strategies, channel data and sensitive business information.",
            },
            termination: {
                title: isPortuguese ? "8. Rescisão" : "8. Termination",
                content: isPortuguese
                    ? "Qualquer parte pode rescindir os serviços mediante aviso prévio. Trabalhos em andamento serão finalizados ou compensados proporcionalmente."
                    : "Either party may terminate services with prior notice. Work in progress will be completed or compensated proportionally.",
            },
            contact: {
                title: isPortuguese ? "9. Contato" : "9. Contact",
                content: isPortuguese
                    ? "Para questões sobre estes termos, entre em contato: gabrieltothgoncalves@gmail.com ou WhatsApp: +55 11 93619-1346"
                    : "For questions about these terms, contact us: gabrieltothgoncalves@gmail.com or WhatsApp: +55 11 93619-1346",
            },
        },
    }

    return (
        <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-12">
            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-8">
                    <header className="mb-8">
                        <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">
                            {content.title}
                        </h1>
                        <p className="text-gray-600 dark:text-gray-300">
                            {content.lastUpdated}
                        </p>
                    </header>

                    <div className="space-y-8">
                        {/* Introduction */}
                        <section>
                            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
                                {content.sections.intro.title}
                            </h2>
                            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                                {content.sections.intro.content}
                            </p>
                        </section>

                        {/* Services */}
                        <section>
                            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
                                {content.sections.services.title}
                            </h2>
                            <ul className="space-y-2 text-gray-700 dark:text-gray-300">
                                {content.sections.services.content.map(
                                    (item, index) => (
                                        <li key={index}>{item}</li>
                                    )
                                )}
                            </ul>
                        </section>

                        {/* Obligations */}
                        <section>
                            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
                                {content.sections.obligations.title}
                            </h2>
                            <ul className="space-y-2 text-gray-700 dark:text-gray-300">
                                {content.sections.obligations.content.map(
                                    (item, index) => (
                                        <li key={index}>{item}</li>
                                    )
                                )}
                            </ul>
                        </section>

                        {/* Payment */}
                        <section>
                            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
                                {content.sections.payment.title}
                            </h2>
                            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                                {content.sections.payment.content}
                            </p>
                        </section>

                        {/* Liability */}
                        <section>
                            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
                                {content.sections.liability.title}
                            </h2>
                            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                                {content.sections.liability.content}
                            </p>
                        </section>

                        {/* Intellectual Property */}
                        <section>
                            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
                                {content.sections.intellectual.title}
                            </h2>
                            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                                {content.sections.intellectual.content}
                            </p>
                        </section>

                        {/* Confidentiality */}
                        <section>
                            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
                                {content.sections.confidentiality.title}
                            </h2>
                            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                                {content.sections.confidentiality.content}
                            </p>
                        </section>

                        {/* Termination */}
                        <section>
                            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
                                {content.sections.termination.title}
                            </h2>
                            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                                {content.sections.termination.content}
                            </p>
                        </section>

                        {/* Contact */}
                        <section>
                            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
                                {content.sections.contact.title}
                            </h2>
                            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                                {content.sections.contact.content}
                            </p>
                        </section>
                    </div>

                    <footer className="mt-12 pt-8 border-t border-gray-200 dark:border-gray-700">
                        <p className="text-sm text-gray-500 dark:text-gray-400 text-center">
                            © 2024 Gabriel Toth Gonçalves.{" "}
                            {isPortuguese
                                ? "Todos os direitos reservados."
                                : "All rights reserved."}
                        </p>
                    </footer>
                </div>
            </div>
        </div>
    )
}
