import EditorsLanding from "@/components/landing/editors-landing"
import { type Locale } from "@/lib/i18n"
import { type Metadata } from "next"

interface PageProps {
    params: Promise<{ locale: Locale }>
}

export async function generateMetadata({
    params,
}: PageProps): Promise<Metadata> {
    const { locale } = await params
    const isPortuguese = locale === "pt-BR"

    return {
        title: isPortuguese
            ? "Trabalhe Como Editor - Gabriel Toth"
            : "Work as Editor - Gabriel Toth",
        description: isPortuguese
            ? "Junte-se à nossa equipe de editores e ganhe 90% do AdSense gerado pelos vídeos que você editar. Trabalho flexível e pagamento por performance."
            : "Join our team of editors and earn 90% of AdSense generated by videos you edit. Flexible work and performance-based payment.",
        keywords: isPortuguese
            ? "editor de vídeo, trabalho remoto, edição youtube, pagamento por performance, adsense"
            : "video editor, remote work, youtube editing, performance payment, adsense",
        openGraph: {
            title: isPortuguese
                ? "Trabalhe Como Editor - Gabriel Toth"
                : "Work as Editor - Gabriel Toth",
            description: isPortuguese
                ? "Ganhe 90% do AdSense dos vídeos que você editar"
                : "Earn 90% of AdSense from videos you edit",
            type: "website",
            locale: locale,
        },
    }
}

export default async function EditorsPage({ params }: PageProps) {
    const { locale } = await params

    return <EditorsLanding locale={locale} />
}
